---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: lint-go
    image: ablab/golangci-lint
    commands:
      - go vet ./...
      - golint ./...
      - golangci-lint run --skip-dirs frontend --timeout 60m --enable-all
      - spaghetti-cutter
    volumes:
      - name: go-pkg-mod
        path: /go/pkg/mod
  - name: lint-svelte
    image: mhart/alpine-node:14
    commands:
      - cd frontend
      - npm ci
      - npm run validate
  - name: test-go
    image: golang:1-alpine
    commands:
      - CGO_ENABLED=0 go test -json -coverprofile=coverage.out $(go list ./... | grep -v /frontend/) >tests.json
    volumes:
      - name: go-pkg-mod
        path: /go/pkg/mod
  - name: tag
    image: busybox
    commands:
      - echo -n "${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}" > .tags
      - if [ ${DRONE_BRANCH} = "master" ]; then echo -n ',stable,latest' >> .tags; else echo -n ',dev' >> .tags; fi
    depends_on:
      - lint-go
      - lint-svelte
      - test-go
  - name: build
    image: plugins/docker
    settings:
      repo: ablab/lazarette
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    depends_on:
      - tag
  # - name: deploy
  #   image: quay.io/honestbee/drone-kubernetes
  #   settings:
  #     kubernetes_server:
  #       from_secret: deploy_server
  #     kubernetes_cert:
  #       from_secret: deploy_cert
  #     kubernetes_token:
  #       from_secret: deploy_token
  #     repo: ablab/lazarette
  #     tag: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
  #     deployment: lazarette
  #     container: lazarette
  #   depends_on:
  #     - build
  #   when:
  #     branch:
  #       - master
  #     event:
  #       - push

volumes:
  - name: go-pkg-mod
    host:
      path: /tmp/cache/${DRONE_REPO}/go
