---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: lint-go
    image: golangci/golangci-lint:latest-alpine
    commands:
      - golangci-lint run --enable-all
  - name: lint-svelte
    image: mhart/alpine-node:14
    commands:
      - cd frontend
      - npm run validate
  - name: tag
    image: busybox
    commands:
      - echo -n "${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}" > .tags
      - if [ ${DRONE_BRANCH} = "master" ]; then echo -n ',stable,latest' >> .tags; else echo -n ',dev' >> .tags; fi
    depends_on:
      - lint-go
      - lint-svelte
  - name: build
    image: plugins/docker
    settings:
      registry: cr.ablab.io
      repo: cr.ablab.io/kve
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    depends_on:
      - tag
  - name: deploy
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server:
        from_secret: deploy_server
      kubernetes_cert:
        from_secret: deploy_cert
      kubernetes_token:
        from_secret: deploy_token
      repo: cr.ablab.io/kve
      tag: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      deployment: kve
      container: kve
    depends_on:
      - build
    when:
      branch:
        - master
      event:
        - push
