---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: lint-go
    image: golangci/golangci-lint:latest-alpine
    commands:
      - go get -u golang.org/x/lint/golint
      - go get -u github.com/flowdev/spaghetti-cutter
      - go vet ./...
      - golint ./...
      - golangci-lint run --skip-dirs frontend --timeout 60m --enable-all
      - go run github.com/flowdev/spaghetti-cutter
  - name: lint-svelte
    image: mhart/alpine-node:14
    commands:
      - cd frontend
      - npm ci
      - npm run validate
  - name: tag
    image: busybox
    commands:
      - echo -n "${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}" > .tags
      - if [ ${DRONE_BRANCH} = "master" ]; then echo -n ',stable,latest' >> .tags; else echo -n ',dev' >> .tags; fi
    depends_on:
      - lint-go
      - lint-svelte
  - name: build
    image: plugins/docker
    settings:
      repo: ablab/lazarette
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    depends_on:
      - tag
  # - name: deploy
  #   image: quay.io/honestbee/drone-kubernetes
  #   settings:
  #     kubernetes_server:
  #       from_secret: deploy_server
  #     kubernetes_cert:
  #       from_secret: deploy_cert
  #     kubernetes_token:
  #       from_secret: deploy_token
  #     repo: ablab/lazarette
  #     tag: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
  #     deployment: lazarette
  #     container: lazarette
  #   depends_on:
  #     - build
  #   when:
  #     branch:
  #       - master
  #     event:
  #       - push
