apiVersion: v1
kind: ServiceAccount
metadata:
  name: kve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kve
rules:
  - apiGroups:
      - ""
      - "storage.k8s.io"
    resources:
      - storageclasses
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kve
subjects:
  - kind: ServiceAccount
    name: kve
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: kve
  namespace: default
spec:
  containers:
    - image: ablab/kve-dev
      imagePullPolicy: Always
      name: kve
      volumeMounts:
        - mountPath: /app
          name: app
  restartPolicy: Never
  serviceAccountName: kve
  volumes:
    - hostPath:
        path: /app
        type: ""
      name: app
