apiVersion: v1
kind: ServiceAccount
metadata:
  name: lazarette
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lazarette
rules:
  - apiGroups:
      - ""
      - "storage.k8s.io"
    resources:
      - storageclasses
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lazarette
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lazarette
subjects:
  - kind: ServiceAccount
    name: lazarette
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: lazarette
  namespace: default
spec:
  containers:
    - image: ablab/lazarette-dev
      imagePullPolicy: Always
      name: lazarette
      env:
        - name: MATRIX
          value: "true"
        - name: PUBLIC_DIR
          value: frontend/public
      volumeMounts:
        - mountPath: /app
          name: app
      ports:
        - name: http
          containerPort: 3000
          hostPort: 3000
        - name: livereload
          containerPort: 35729
          hostPort: 35729
  restartPolicy: Never
  serviceAccountName: lazarette
  volumes:
    - hostPath:
        path: /app
        type: ""
      name: app
