name: build

on:
  push:
  pull_request:

jobs:
  go-checks:
    name: go-checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up linters
        run: |
          GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          go get -u golang.org/x/lint/golint
          go get -u github.com/flowdev/spaghetti-cutter

      - name: Check out
        uses: actions/checkout@v2

      - name: Lint
        run: |
          go vet ./...
          golint -set_exit_status ./...
          golangci-lint run --skip-dirs frontend --timeout 60m --enable-all
          spaghetti-cutter

      - name: Test
        run: go test -race -json -coverprofile=coverage.out $(go list ./... | grep -v /frontend/) >tests.json

  svelte-checks:
    name: svelte-checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check out
        uses: actions/checkout@v2

      - name: Validate
        run: |
          cd frontend
          npm ci
          npm run validate

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [go-checks, svelte-checks]
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ablab/lazarette:latest
