name: lazarette

on:
  push:
  pull_request:

jobs:
  lazarette:
    name: go
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: set up linters
        run: |
          GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          go get -u golang.org/x/lint/golint
          go get -u github.com/flowdev/spaghetti-cutter

      - name: check out
        uses: actions/checkout@v2

      - name: lint
        run: |
          go vet ./...
          golint -set_exit_status ./...
          golangci-lint run --skip-dirs frontend --timeout 60m --enable-all
          spaghetti-cutter

      - name: test
        run: go test -race -json -coverprofile=coverage.out $(go list ./... | grep -v /frontend/) >tests.json
